[package]
name = "distributor"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.5.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=1.5.0"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
casm = true